# Brewfile for dotfiles setup

# CLI Tools
brew "git"
brew "stow"
brew "zsh"
brew "ripgrep"
brew "pyenv"
brew "xz"
brew "starship"
brew "node"
brew "yarn"
cask "veracrypt"
cask "little-snitch"

# Applications
cask "intellij-idea"
cask "raycast"
cask "slack"
cask "spotify"
cask "viber"
cask "whatsapp"
cask "bitwarden"
cask "docker"
cask "postman"
cask "telegram"
cask "simplenote"
cask "snipaste"
cask "logi-options+"
cask "google-chrome"
cask "omnidisksweeper"
cask "microsoft-teams"
cask "grammarly-desktop"
cask "openvpn-connect"
cask "openlens"
cask "visual-studio-code"
cask "cursor"
cask "tailscale"
# Note: klogg may need manual installation or different source